version: "3.9"

services:
  postgres:
    image: postgres:17.0
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: strim
      LANG: en_US.utf8
      TZ: Europe/Oslo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata17:
    driver: local
