apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: strim-backend
  namespace: delta
  labels:
    team: delta
spec:
  accessPolicy:
    inbound:
      rules:
        - application: strim-frontend
  image: {{image}}
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: strim
  azure:
    application:
      enabled: true
      allowAllUsers: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  liveness:
    initialDelay: 30
    periodSeconds: 10
    timeout: 5
    failureThreshold: 12
  readiness:
    initialDelay: 30
    periodSeconds: 10
    timeout: 5