apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: strim-backend
  namespace: delta
  labels:
    team: delta
spec:
  image: {{image}}
  accessPolicy:
    inbound:
      rules:
        - application: strim-frontend
  port: 8080
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: strim
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  liveness:
    path: /internal/actuator/health
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
