apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: strim-backend
  namespace: delta
  labels:
    team: delta
spec:
  ingresses:
    - https://strim-backend.intern.nav.no
  image: {{image}}
  accessPolicy:
    inbound:
      rules:
        - application: strim-frontend
  port: 8080
#  envFrom:
#  - secret: google-sql-strim-backend
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        # TODO: Migrere over til større database, micro er ikke tilstrekkelig
        tier: db-f1-micro
        databases:
          - name: strim
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
