CREATE SCHEMA IF NOT EXISTS public;
SET SEARCH_PATH TO public;

CREATE TABLE IF NOT EXISTS EVENTS
(
    ID                UUID PRIMARY KEY,
    TITLE             VARCHAR(255) NOT NULL,
    DESCRIPTION       TEXT,
    VIDEO_URL         VARCHAR(255),
    START_TIME        TIMESTAMP    NOT NULL,
    END_TIME          TIMESTAMP    NOT NULL,
    LOCATION          VARCHAR(255) NOT NULL,
    IS_PUBLIC          BOOLEAN      NOT NULL,
    PARTICIPANT_LIMIT INTEGER      NOT NULL,
    SIGNUP_DEADLINE   TIMESTAMP
);
